/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/joMbbbDpUFO
 */
import { Button } from "@/components/ui/button"

export function Header() {
  return (
    <div className="bg-black p-4 flex justify-between items-center">
      <div>
        <h3 className="text-2xl font-medium">
          TestHub
        </h3>
      </div>
      <div className="flex gap-4">
        <Button className="border-white text-white bg-transparent" variant="outline">
          Регистрация
        </Button>
        <Button className="bg-cyan-500 text-white" variant="default">
          Войти
        </Button>
      </div>
    </div>
  )
}
