/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ldRKyYorzzl
 */
import Link from "next/link"

export function Hero() {
  return (
    <section className="w-full bg-black py-8 md:py-12 lg:py-24 xl:py-32">
      <div className="mx-auto container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter text-white sm:text-4xl md:text-5xl lg:text-6xl/none">
              Добро пожаловать в QuizMaster
            </h1>
            <p className="mx-auto max-w-[700px] text-cyan-500 md:text-xl dark:text-cyan-400">
              Улучшите свои знания, весело проводя время. Готовы начать?
            </p>
          </div>
          <div className="space-x-4">
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md bg-cyan-500 px-4 py-2 text-sm font-medium text-black shadow transition-colors hover:bg-cyan-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-cyan-700 disabled:pointer-events-none disabled:opacity-50"
              href="/quiz"
            >
              Начать викторину
            </Link>
          </div>
        </div>
      </div>
    </section>
  )
}
