/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n67Kxoyx7P3
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function Landing() {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white">
      <header className="flex items-center justify-between px-6 py-4">
        <div className="flex items-center space-x-2">
          <svg
            className=" h-8 w-8 text-cyan-500"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M3 21c3 0 7-1 7-8V5c0-1.25-.756-2.017-2-2H4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2 1 0 1 0 1 1v1c0 1-1 2-2 2s-1 .008-1 1.031V20c0 1 0 1 1 1z" />
            <path d="M15 21c3 0 7-1 7-8V5c0-1.25-.757-2.017-2-2h-4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2h.75c0 2.25.25 4-2.75 4v3c0 1 0 1 1 1z" />
          </svg>
          <span className="text-2xl font-semibold">TestHub</span>
        </div>
        <nav className="space-x-4">
          <Link className="text-lg font-medium" href="#">
            Войти
          </Link>
          <Link className="text-lg font-medium" href="#">
            Регистрация
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="text-center py-16">
          <h1 className="text-4xl font-bold">Welcome to Quiz App</h1>
          <p className="text-lg mt-4 mx-auto w-3/4">
            The best platform to test your knowledge on various subjects.
          </p>
        </section>
        <section className="grid grid-cols-3 gap-6 p-6">
          <div className="flex flex-col items-center space-y-2">
            <svg
              className=" h-12 w-12 text-cyan-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m16 6 4 14" />
              <path d="M12 6v14" />
              <path d="M8 8v12" />
              <path d="M4 4v16" />
            </svg>
            <h3 className="text-xl font-semibold">Variety of Topics</h3>
            <p className="text-center">Choose from a wide range of topics.</p>
          </div>
          <div className="flex flex-col items-center space-y-2">
            <svg
              className=" h-12 w-12 text-cyan-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <line x1="10" x2="14" y1="2" y2="2" />
              <line x1="12" x2="15" y1="14" y2="11" />
              <circle cx="12" cy="14" r="8" />
            </svg>
            <h3 className="text-xl font-semibold">Timed Quizzes</h3>
            <p className="text-center">
              Challenge yourself with timed quizzes.
            </p>
          </div>
          <div className="flex flex-col items-center space-y-2">
            <svg
              className=" h-12 w-12 text-cyan-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
              <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
              <path d="M4 22h16" />
              <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
              <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
              <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
            </svg>
            <h3 className="text-xl font-semibold">Leaderboards</h3>
            <p className="text-center">
              Compete with others on our leaderboards.
            </p>
          </div>
        </section>
        <section className="flex flex-col items-center py-16">
          <h2 className="text-3xl font-bold">Ready to challenge yourself?</h2>
          <Button
            className={
              " py-3 bg-cyan-500 hover:bg-cyan-700 focus:ring-cyan-400 focus:ring-offset-cyan-200 text-white transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg col-span-2"
            }
            type="submit"
          >
            Начать
          </Button>
        </section>
      </main>
      <footer className="flex flex-col items-center py-4">
        <div className="flex space-x-4">
          <Link href="#">
            <svg
              className=" h-6 w-6"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
            </svg>
          </Link>
          <Link href="#">
            <svg
              className=" h-6 w-6"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
            </svg>
          </Link>
          <Link href="#">
            <svg
              className=" h-6 w-6"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect height="20" rx="5" ry="5" width="20" x="2" y="2" />
              <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
              <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
            </svg>
          </Link>
        </div>
        <p className="text-xs mt-2">© 2023 Quiz App. All rights reserved.</p>
      </footer>
    </div>
  );
}
