/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z7AmncMqSpk
 */


export function Quizes() {
  return (
    <section className="w-full h-screen bg-black text-white p-4 md:p-6 lg:p-8">
      <h1 className="text-4xl md:text-5xl lg:text-6xl text-center mb-8">Quizzes</h1>
      <div className="grid gap-6 md:gap-8 lg:gap-10 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        <div className="rounded-lg bg-white text-black p-6 md:p-8 lg:p-10">
          <h2 className="text-2xl md:text-3xl lg:text-4xl text-cyan-500 mb-4">Quiz 1</h2>
          <p className="text-lg md:text-xl lg:text-2xl">This is a description of Quiz 1.</p>
        </div>
        <div className="rounded-lg bg-white text-black p-6 md:p-8 lg:p-10">
          <h2 className="text-2xl md:text-3xl lg:text-4xl text-cyan-500 mb-4">Quiz 2</h2>
          <p className="text-lg md:text-xl lg:text-2xl">This is a description of Quiz 2.</p>
        </div>
        <div className="rounded-lg bg-white text-black p-6 md:p-8 lg:p-10">
          <h2 className="text-2xl md:text-3xl lg:text-4xl text-cyan-500 mb-4">Quiz 3</h2>
          <p className="text-lg md:text-xl lg:text-2xl">This is a description of Quiz 3.</p>
        </div>
        <div className="rounded-lg bg-white text-black p-6 md:p-8 lg:p-10">
          <h2 className="text-2xl md:text-3xl lg:text-4xl text-cyan-500 mb-4">Quiz 4</h2>
          <p className="text-lg md:text-xl lg:text-2xl">This is a description of Quiz 4.</p>
        </div>
      </div>
    </section>
  )
}
