"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UF96Ui54rHv
 */
import { Button } from "@/components/ui/button";
import { useQuiz } from "@/hooks/hooks";
import { useRouter } from "next/navigation";

import React, { useEffect } from "react";
interface QuizProps {
  params: { id: string; questionId: string };
}

export const Quiz: React.FC<QuizProps> = ({ params }) => {
  const quiz = useQuiz(params.id);
  const router = useRouter();
  const isLast = false;

  function next() {
    router.push(`/quiz/${params.id}/${+params.questionId + 1}`);
  }
  function prev() {
    router.push(`/quiz/${params.id}/${+params.questionId - 1}`);
  }

  useEffect(() => {
    console.log(params);
  }, []);

  return (
    <div className="min-h-screen bg-black text-white py-6 flex flex-col justify-center sm:py-12">
      <div className="relative w-full py-3 sm:max-w-xl sm:mx-auto">
        <div className="absolute inset-0 bg-gradient-to-r from-teal-500 to-cyan-600 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl" />
        <div className="relative px-4 py-10 bg-zinc-950 shadow-lg sm:rounded-3xl sm:p-20">
          <h1 className="text-4xl font-bold text-center mb-4">Quiz</h1>
          <div className="mb-5">
            <label className="block mb-2">Question 1</label>
            <div className="gap-4 grid grid-cols-2">
              <button
                type="button"
                className="w-full p-4 text-left rounded-lg bg-zinc-800 hover:bg-zinc-700 transition-colors duration-200"
              >
                Option 1
              </button>
              <button
                type="button"
                className="w-full p-4 text-left rounded-lg bg-zinc-800 hover:bg-zinc-700 transition-colors duration-200"
              >
                Option 2
              </button>
              <button
                type="button"
                className="w-full p-4 text-left rounded-lg bg-zinc-800 hover:bg-zinc-700 transition-colors duration-200"
              >
                Option 3
              </button>
              <button
                type="button"
                className="w-full p-4 text-left rounded-lg bg-zinc-800 hover:bg-zinc-700 transition-colors duration-200"
              >
                Option 4
              </button>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4 mt-6">
            <Button
              onClick={prev}
              className=" w-full py-3 bg-gray-600 hover:bg-gray-700 focus:ring-gray-500 focus:ring-offset-gray-200 text-white transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg "
              type="submit"
            >
              Назад
            </Button>
            <Button
              onClick={next}
              className="col-span-2 w-full py-3 bg-cyan-600 hover:bg-cyan-700 focus:ring-cyan-500 focus:ring-offset-cyan-200 text-white transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg "
              type="submit"
            >
              {isLast ? "Отправить" : "Следующий"}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};
