/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QSMfupuqaFz
 */
import { Button } from "@/components/ui/button";
import { Input } from "../ui/input";

export function QuizCreate() {
  return (
    <div className="min-h-screen bg-black text-white py-6 flex flex-col justify-center sm:py-12">
      <div className="relative w-full py-3 sm:max-w-xl sm:mx-auto">
        <div className="absolute inset-0 bg-gradient-to-r from-teal-500 to-cyan-600 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl" />
        <div className="relative px-4 py-10 bg-zinc-950 shadow-lg sm:rounded-3xl sm:p-20">
          <h1 className="text-4xl font-bold text-center mb-4">Create Quiz</h1>
          <form>
            <div className="mb-5">
              <label className="block font-medium mb-2">Quiz Name</label>
              <Input
                className="w-full px-4 py-6 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="Enter Quiz Name"
                type="text"
              />
            </div>
            <div className="mb-3">
              <div>
                <label className="block font-medium mb-2">Question 1</label>
                <Input
                  className="w-full px-4 py-4 bg-zinc-900 rounded-lg focus:border-transparent"
                  placeholder="Enter question"
                  type="text"
                />
              </div>
              <div className="space-y-4 mt-4">
                <div className="space-y-2">
                  <div className="relative flex">
                    <label
                      className="relative flex items-center p-2 pr-2 rounded-full cursor-pointer"
                      htmlFor="checkbox"
                      data-ripple-dark="true"
                    >
                      <input
                        type="radio"
                        className="before:content[''] peer relative h-5 w-5 cursor-pointer appearance-none rounded-md border border-blue-gray-200 transition-all before:absolute before:top-2/4 before:left-2/4 before:block before:h-12 before:w-12 before:-translate-y-2/4 before:-translate-x-2/4 before:rounded-full before:bg-blue-gray-500 before:opacity-0 before:transition-opacity checked:border-cyan-600 checked:bg-cyan-600 checked:before:bg-cyan-600 hover:before:opacity-10"
                        id="checkbox"
                      />
                      <div className="absolute text-white transition-opacity opacity-0 pointer-events-none top-2/4 left-2/4 -translate-y-2/4 -translate-x-2/4 peer-checked:opacity-100">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          className="h-3.5 w-3.5"
                          viewBox="0 0 20 20"
                          fill="currentColor"
                          stroke="currentColor"
                          stroke-width="1"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clip-rule="evenodd"
                          ></path>
                        </svg>
                      </div>
                    </label>
                    <Input
                      className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent ml-3"
                      placeholder="Option 1"
                      type="text"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="h-2 mt-4 mb-2 group hover:h-3 transition-all relative">
              <div className="absolute -translate-y-1/2 border-solid border-l-zinc-900 border-l-8 border-y-transparent border-y-8 border-r-0 group-hover:border-l-zinc-800 transition-all"></div>
              <div className="h-0.5 -translate-y-1/2 bg-zinc-900  group-hover:h-1 group-hover:bg-zinc-800 transition-all">
                <div className="absolute left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-0  group-hover:opacity-100 transition-all">
                  add
                </div>
              </div>
            </div>
            <div className="mb-3">
              <div>
                <label className="block font-medium mb-2">Question 2</label>
                <Input
                  className="w-full px-4 py-4 bg-zinc-900 rounded-lg focus:border-transparent"
                  placeholder="Enter question"
                  type="text"
                />
              </div>
              <div className="space-y-4 mt-4 ml-4">
                <div className="space-y-2">
                  <Input
                    className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                    placeholder="Option 1"
                    type="text"
                  />
                  <Input
                    className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                    placeholder="Option 2"
                    type="text"
                  />
                  <Input
                    className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                    placeholder="Option 3"
                    type="text"
                  />
                  <Input
                    className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                    placeholder="Option 4"
                    type="text"
                  />
                </div>
              </div>
            </div>
            <div className="h-2 mt-4 mb-2 group hover:h-3 transition-all relative">
              <div className="absolute -translate-y-1/2 border-solid border-l-zinc-900 border-l-8 border-y-transparent border-y-8 border-r-0 group-hover:border-l-zinc-800 transition-all"></div>
              <div className="h-0.5 -translate-y-1/2 bg-zinc-900  group-hover:h-1 group-hover:bg-zinc-800 transition-all">
                <div className="absolute left-1/2 -translate-x-1/2 -translate-y-1/2 opacity-0  group-hover:opacity-100 transition-all">
                  add
                </div>
              </div>
            </div>
            <Button
              className="w-full py-3 bg-cyan-600 hover:bg-cyan-700 focus:ring-cyan-500 focus:ring-offset-cyan-200 text-white transition ease-in duration-200 text-center text-base font-semibold shadow-md focus:outline-none focus:ring-2 focus:ring-offset-2 rounded-lg "
              type="submit"
            >
              Create Quiz
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}
