/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8LVSewNH9qw
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Register() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-black">
      <div className="w-full max-w-sm shadow-lg rounded-lg overflow-hidden md:max-w-lg">
        <div className="px-10 py-12 bg-zinc-950 text-white">
          <h1 className="text-3xl font-bold text-center">Register</h1>
          <form className="mt-6 space-y-6">
            <div>
              <label className="block text-sm font-medium">Username</label>
              <Input
                className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="Username"
                type="text"
              />
            </div>
            <div>
              <label className="block text-sm font-medium">Email</label>
              <Input
                className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="Email"
                type="email"
              />
            </div>
            <div>
              <label className="block text-sm font-medium">Password</label>
              <Input
                className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="Password"
                type="password"
              />
            </div>
            <div>
              <Button className="w-full py-2 bg-zinc-700 rounded-lg text-white" type="submit">
                Register
              </Button>
            </div>
          </form>
        </div>
        <div className="px-10 py-4 bg-zinc-900 text-center text-white">
          <span>Already have an account?</span>
          <Link className="text-blue-500 hover:text-blue-700 ml-2" href="#">
            Login
          </Link>
        </div>
      </div>
    </div>
  )
}
