"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8LVSewNH9qw
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

import { useForm, SubmitHandler } from "react-hook-form";
import { RegisterRequest } from "@/interfaces/AuthInterfaces";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import AuthService from "@/services/AuthService";
import axios from "axios";
import { useState } from "react";
import { useRouter } from "next/navigation";

const schema = yup.object({
  email: yup
    .string()
    .email("Введите корректную почту")
    .required("Это обязательное поле"),
  password: yup
    .string()
    .min(8, "Пароль должен быть от 8 символов")
    .required("Это обязательное поле"),
  username: yup.string().required("Это обязательное поле"),
});

export function Register() {
  const router = useRouter();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<RegisterRequest>({
    resolver: yupResolver(schema),
  });
  const onSubmit: SubmitHandler<RegisterRequest> = (data) => reg(data);

  const [error, setError] = useState("");

  async function reg(data: RegisterRequest) {
    try {
      await AuthService.register(data);
      await AuthService.login(data);
      router.push("/");
    } catch (error) {
      if (axios.isAxiosError(error)) {
        if (error.response?.data?.message == "email already used") {
          setError("Почта уже занята, выберите другую");
        }
      }
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-black">
      <div className="w-full max-w-sm shadow-lg rounded-lg overflow-hidden md:max-w-lg">
        <div className="px-10 py-12 bg-zinc-950 text-white">
          <h1 className="text-3xl font-bold text-center">Регистрация</h1>
          {error && (
            <p className="text-red-200 text-lg text-center my-2">{error}</p>
          )}
          <form onSubmit={handleSubmit(onSubmit)} className="mt-6 space-y-6">
            <div>
              <label className="block text-sm font-medium">
                Имя
                <span className="ml-2 text-red-200 font-normal">
                  {errors.username?.message}
                </span>
              </label>
              <Input
                {...register("username", { required: true })}
                className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="Ваня"
                type="text"
              />
            </div>
            <div>
              <label className="block text-sm font-medium">
                Email{" "}
                <span className="ml-2 text-red-200 font-normal">
                  {errors.email?.message}
                </span>
              </label>
              <Input
                {...register("email", { required: true })}
                className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="ivan@user@mail.example"
                type="email"
              />
            </div>
            <div>
              <label className="block text-sm font-medium">
                Пароль{" "}
                <span className="ml-2 text-red-200 font-normal">
                  {errors.password?.message}
                </span>
              </label>
              <Input
                {...register("password", { required: true })}
                className="w-full px-4 py-2 bg-zinc-900 rounded-lg focus:border-transparent"
                placeholder="******"
                type="password"
              />
            </div>
            <div>
              <Button
                className="w-full py-2 bg-zinc-700 rounded-lg text-white"
                type="submit"
              >
                Зарегистрироваться
              </Button>
            </div>
          </form>
        </div>
        <div className="px-10 py-4 bg-zinc-900 text-center text-white">
          <span>Уже есть аккаунт?</span>
          <Link className="text-blue-500 hover:text-blue-700 ml-2" href="#">
            Войти
          </Link>
        </div>
      </div>
    </div>
  );
}
