/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yec65EZ2RIH
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function CreateSection() {
  return (
    <section className="w-full bg-black text-white py-8 md:py-16 lg:py-24">
      <div className="container mx-auto px-4 md:px-8 lg:px-12">
        <h2 className="font-bold text-center text-2xl md:text-3xl lg:text-4xl text-cyan-400">
          Создай свою собственную викторину
        </h2>
        <p className="mt-4 text-center text-base lg:text-xl">
          Преобразуйте свои знания и идеи в увлекательную и захватывающую
          викторину для проверки знаний ваших друзей и семьи.
        </p>
        <div className="mt-8 flex justify-center">
          <Link href={"/quiz/create"}>
            <Button
              className="px-6 py-4 text-base lg:py-6 lg:px-8 lg:text-xl bg-white text-black"
              variant="secondary"
            >
              Начать создание
            </Button>
          </Link>
        </div>
      </div>
    </section>
  );
}
