/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ldRKyYorzzl
 */
import Link from "next/link";
import { Button } from "../../ui/button";

export function Hero() {
  return (
    <section className="w-full bg-black py-8 md:py-12 lg:py-24 xl:py-32">
      <div className="mx-auto container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter text-white sm:text-4xl md:text-5xl lg:text-6xl/none">
              Добро пожаловать в QuizMaster
            </h1>
            <p className="mx-auto max-w-[700px] text-cyan-500 md:text-xl dark:text-cyan-400">
              Улучшите свои знания, весело проводя время. Готовы начать?
            </p>
          </div>
          <div className="space-x-4">
            <Link
              href="/quiz"
            >
              <Button
                className="px-6 py-4 text-base lg:py-6 lg:px-8 lg:text-xl bg-white text-black"
                variant="secondary"
              >
                Начать викторину
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
