// Generated by https://quicktype.io

import { IQuiz } from "./QuizInterfaces";

export interface IUserInfo {
  user: IUser;
  quizzes: IQuiz[];
  results: IResult[];
}

export interface IResult {
  quiz: IQuiz;
  score: number;
  percent: number;
  created_at: string;
}

interface IUser {
  id: number;
  username: string;
  email: string;
  avatar: string;
}
