// Generated by https://quicktype.io

export interface IUserInfo {
  user: IUser;
  quizzes: IQuiz[];
  results: IResult[];
}

interface IQuiz {
  id: number;
  title: string;
  description: string;
  image: string;
  user_id: number;
  created_at: string;
}

interface IResult {
  quiz: IQuiz;
  score: number;
  percent: number;
  created_at: string;
}

interface IUser {
  id: number;
  username: string;
  email: string;
  avatar: string;
}
