"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/z7AmncMqSpk
 */

import { IQuiz } from "@/interfaces/QuizInterfaces";
import QuizService from "@/services/QuizService";
import Link from "next/link";
import { useEffect, useState } from "react";
import { url } from "@/utils/http";
import Image from "next/image";
import QuizImage from "../Base/quiz-image";
import { Header } from "../Base/header";
import QuizItem from "../Quiz/QuizItem";

export function Quizes() {
  const [quizes, setQuizes] = useState<IQuiz[]>([]);
  useEffect(() => {
    QuizService.fetchQuizes().then((resp) => setQuizes(resp.data));
  }, []);

  return (
    <div>
      <Header />
      <section className="w-full min-h-screen bg-black text-white p-4 md:p-6 lg:p-8">
        <div className="grid gap-6 md:gap-8 lg:gap-10 items-stretch grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {quizes.map((el) => (
            <QuizItem key={el.id} quiz={el} />
          ))}
        </div>
      </section>
    </div>
  );
}
