"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8LVSewNH9qw
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";

import { useForm, SubmitHandler } from "react-hook-form";
import { RegisterRequest } from "@/interfaces/AuthInterfaces";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import AuthService from "@/services/AuthService";
import axios from "axios";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Lights, { LightProps } from "../Background/Lights";
import Card from "@/components/ui/Card";
import AuthInput from "../AuthForm/AuthInput";
import AuthFormLayout from "../AuthForm/AuthFormLayout";
import AuthFormBottom from "../AuthForm/AuthFormBottom";

const lights: LightProps[] = [
  {
    color: "sky",
    pos: "opacity-50 top-1/2 left-1/2",
    size: "medium",
  },
  {
    color: "teal",
    pos: "opacity-50 top-1/3 right-0",
    size: "small",
    translateToRight: true,
  },
  {
    color: "sky",
    pos: "opacity-50 bottom-0 left-0",
    size: "medium",
    translateToBottom: true,
  },
];

const schema = yup.object({
  email: yup
    .string()
    .email("Введите корректную почту")
    .required("Это обязательное поле"),
  password: yup
    .string()
    .min(8, "Пароль должен быть от 8 символов")
    .required("Это обязательное поле"),
  username: yup.string().required("Это обязательное поле"),
});

export function Register() {
  const router = useRouter();
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<RegisterRequest>({
    resolver: yupResolver(schema),
  });
  const onSubmit: SubmitHandler<RegisterRequest> = (data) => reg(data);

  const [error, setError] = useState("");

  async function reg(data: RegisterRequest) {
    try {
      await AuthService.register(data);
      await AuthService.login(data);
      router.push("/");
    } catch (error) {
      if (axios.isAxiosError(error)) {
        if (error.response?.data?.message == "email already used") {
          setError("Почта уже занята, выберите другую");
        }
      }
    }
  }

  return (
    <AuthFormLayout
      bottom={
        <AuthFormBottom>
          <span>Уже есть аккаунт?</span>
          <Link
            className="text-blue-500 hover:text-blue-700 ml-2"
            href="/login"
          >
            Войти
          </Link>
        </AuthFormBottom>
      }
    >
      <h1 className="text-3xl font-bold text-center">Регистрация</h1>
      {error && (
        <p className="text-red-200 text-lg text-center my-2">{error}</p>
      )}
      <form onSubmit={handleSubmit(onSubmit)} className="mt-6 space-y-6">
        <AuthInput
          label="Имя"
          registerProps={register("username", { required: true })}
          error={errors.username?.message}
          placeholder="Ваня"
          type="text"
        />
        <AuthInput
          label="Email"
          registerProps={register("email", { required: true })}
          error={errors.email?.message}
          placeholder="ivan@user@mail.example"
          type="email"
        />
        <AuthInput
          label="Пароль"
          registerProps={register("password", { required: true })}
          error={errors.password?.message}
          placeholder="******"
          type="password"
        />
        <div>
          <Button
            className="w-full py-2 bg-zinc-700 rounded-lg text-white"
            type="submit"
          >
            Зарегистрироваться
          </Button>
        </div>
      </form>
    </AuthFormLayout>
  );
}
